neural_field_type: gs
expname: ${neural_field_type}_${task}_${dataset.name}_${dataset.scene}
task: novel_view_synthesis
seed: 42

dataset:
  name: deblur
  root_dir: /home/chenyu/HD_Datasets/datasets/${dataset.name}/real_camera_motion_blur
  scene: ["blurball", "blurbasket", "blurbuick", "blurcoffee", "blurdecoration",
          "blurgirl", "blurheron", "blurparterre", "blurpuppet", "blurstair"]
  train_split: train
  val_split: val
  data_split_json: ""
  factor: 4
  val_interval: 8
  apply_mask: false
  multi_blocks: false
  num_blocks: 1
  scale: false
  rotate: false
  use_manhattan_world: true
  batch_over_images: false
  model_folder: sparse
  init_ply_type: sparse

trainer:
  max_iterations: 20000
  ckpt_path: ""
  no_load_opt: false
  no_load_scheduler: false
  enable_tensorboard: true
  enable_visdom: false
  visdom_server:
  visdom_port:
  n_tensorboard: 100
  n_validation: 10000
  n_checkpoint: 10000
  distributed: false
  excluded_gpus: []
  num_workers: 4
  local_rank: 0

prune:
  iterations: [] # [16000, 24000]
  v_pow: 0.1
  prune_decay: 0.6
  prune_percent: 0.5

optimizer:
  lr:
    # Gaussian centers related.
    position_init: 0.0016
    position_final: 0.000016
    position_delay_mult: 0.01
    position_max_iterations: ${trainer.max_iterations}
    # Exposure related.
    exposure_lr_init: 0.01
    exposure_lr_final: 0.001
    exposure_lr_delay_steps: 0
    exposure_lr_delay_mult: 0
    exposure_max_iterations: ${trainer.max_iterations}
    # Other 3D GS properties.
    feature: 0.0025
    opacity: 0.025
    scaling: 0.005
    quaternion: 0.001
    # Decoupled appearance encoding.
    mask: 0.001
    # Deblur network
    deblur: 0.001

geometry:
  percent_dense: 0.01
  depth_threshold: 0
  coarse-to-fine: false
  sample_more_high_resolution: false
  densify_start_iter: 500
  densify_end_iter: 15000
  opt_pose_start_iter: 3000
  densification_interval: 100
  opacity_reset_interval: 3000
  min_opacity: 0.01  # 0.005
  densify_grad_threshold: 0.0005 # 0.0002 # revised according to `Deblur 3D Gaussian Splatting`
  mask: false
  deblur: true

texture:
  max_sh_degree: 3
  anti_aliasing: false

deblur:
  method: "deblur_3dgs"
  type: "motion_blur"
  position_latent_dim: 3
  view_latent_dim: 10
  net_depth: 3
  net_width: 64
  num_gaussian_sets: 5
  lambda_scale: 0.01
  lambda_position: 0.01
  use_position_offset: true
  max_clamp: 1.1
  # parameters for adding extra points
  extra_points_iteration: 2500
  points_rate: 1.1
  num_extra_points: 200000
  distance: 2
  num_nearest_neighbor: 4
  points_bound: 10

appearance:
  use_trained_exposure: false

pipeline:
  convert_SHs_python: false
  compute_cov3D_python: false
  debug: false

loss:
  lambda_dssim: 0.2
  lambda_scale: 0
  lambda_mask: 0
